#  File Name:         OsvvmScriptsFileCreate.tcl
#  Purpose:           Scripts for running simulations
#  Revision:          OSVVM MODELS STANDARD VERSION
#
#  Maintainer:        Jim Lewis      email:  jim@synthworks.com
#  Contributor(s):
#     Jim Lewis           email:  jim@synthworks.com
#     Markus Ferringer    Patterns for error handling and callbacks, ...
#
#  Description
#    Tcl procedures to Autogenerate Files
#
#  Developed by:
#        SynthWorks Design Inc.
#        VHDL Training Classes
#        OSVVM Methodology and Model Library
#        11898 SW 128th Ave.  Tigard, Or  97223
#        http://www.SynthWorks.com
#
#  Revision History:
#    Date      Version    Description
#     1/2025   2025.01    Initial
#
#
#  This file is part of OSVVM.
#
#  Copyright (c) 2025 by SynthWorks Design Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

package require fileutil
package require huddle
package require yaml

namespace eval ::osvvm {
  # Declare existance as a global, but do not initialize as it will clear it
  variable AnalyzeDict  
  variable AnalyzeOrderList 
  variable SimulateDict 

# -------------------------------------------------
# CreateDryRunDict
#
proc CreateDryRunDict {ProFileToBuild} {
  # Run a build script in dry-run mode and record what it analyzes and simulates.
  #  ProFileToBuild - Path to the build script (`*.pro`) of the design.
  #
  # Replaces the vendor procedures with the recording ones of `VendorScripts_DryRunDict.tcl`, runs [build] on
  # $ProFileToBuild with the build name `CreateDryRunDict` and OSVVM's reports disabled, then sources the active
  # simulator's vendor script again and restores the report setting. Nothing is analyzed or simulated.
  #
  # The recording is stored in three variables of the `::osvvm` namespace:
  #
  # `AnalyzeDict` - Per library, a list of dictionaries with the analyzed file and its language version.
  # `AnalyzeOrderList` - A list of dictionaries with file name, library and VHDL version, in analyze order.
  # `SimulateDict` - Per library, a list of dictionaries with the arguments passed to [simulate].
  #
  # See also: [CreateVhdlLsToml] [CreateAnalyzeOrderCsv] [ProToYaml] [ProToJson]
  
  variable GenerateOsvvmReports
  set SavedGenerateOsvvmReports $GenerateOsvvmReports
  set GenerateOsvvmReports "false"   ;# turn off reports
 
  # initialize dictionaries to empty
  variable AnalyzeDict  [dict create]  ;# empty dictionary
  variable AnalyzeOrderList ""         ;# empty list
  variable SimulateDict [dict create]  ;# empty dictionary
  
  # Create AnalyzeDict and SimulateDict as a recording of 
  source $::OsvvmLibraries/Scripts/VendorScripts_DryRunDict.tcl
  
  build $ProFileToBuild [BuildName CreateDryRunDict]
#  if {$ScriptToRun ne ""} { $ScriptToRun }
  
  # restore settings and tool API actions
  # StartUp  ;# replace source below with StartUp if features beyond VendorScripts_xxx.tcl are changed
  source $::OsvvmLibraries/Scripts/VendorScripts_${::osvvm::ScriptBaseName}.tcl
  set GenerateOsvvmReports $SavedGenerateOsvvmReports  ;# restore reports
}

# -------------------------------------------------
# CreateVhdlLsToml for VHDL LS
#
proc CreateVhdlLsToml {ProFileToBuild {FileNameAndPath "./vhdl_ls.toml"}} {
  # Create a VHDL-LS configuration file for a build script.
  #  ProFileToBuild  - Path to the build script (`*.pro`) of the design.
  #  FileNameAndPath - Path of the configuration file to write.
  #
  # Runs [CreateDryRunDict] on $ProFileToBuild and writes a `vhdl_ls.toml` file for the VHDL language server VHDL-LS:
  # a `[libraries]` table listing the analyzed files of each library.
  #
  # See also: [CreateDryRunDict]
  variable AnalyzeDict

  # Create AnalyzeDict for the ProFileToBuild script
  CreateDryRunDict $ProFileToBuild

  set TomlFile      [open [file normalize $FileNameAndPath] w]

  puts $TomlFile "# Generated by OSVVM's CreateVhdlLsToml"
  puts $TomlFile "\[libraries\]"

  foreach key [dict keys $AnalyzeDict] {
    # Print library name
    set FileList [dict get $AnalyzeDict $key]
    puts $TomlFile "${key}.files = \["
    foreach FileDict $FileList {
      puts $TomlFile "  '[dict get $FileDict FileName]',"
    }
    puts $TomlFile "\]"
    # mark things from OSVVM libraries as thrid party
  }
  close $TomlFile
}

proc CreateAnalyzeOrderCsv {ProFileToBuild {FileNameAndPath "./AnalyzeOrder.csv"}} {
  # Create a CSV file listing the files of a build script in analyze order.
  #  ProFileToBuild  - Path to the build script (`*.pro`) of the design.
  #  FileNameAndPath - Path of the CSV file to write.
  #
  # Runs [CreateDryRunDict] on $ProFileToBuild and writes the analyzed files in analyze order, one per line, separated
  # by commas.
  #
  # See also: [CreateDryRunDict]
  variable AnalyzeOrderList

  # Create AnalyzeDict for the ProFileToBuild script
  CreateDryRunDict $ProFileToBuild

  set CsvFile     [open [file normalize $FileNameAndPath] w]

#  puts $CsvFile "# Generated by OSVVM's CreateAnalyzeOrderCsv"

  foreach FileDict $::osvvm::AnalyzeOrderList {
    if {[info exists PrintString]} {puts $CsvFile "${PrintString},"}
    set PrintString [dict get $FileDict FileName]
    # puts $CsvFile "[dict get $FileDict FileName],"
  }
  puts $CsvFile "${PrintString}"
  close $CsvFile 
}

proc ProToYaml {ProFileToBuild {FilePath "."}} {
  # Translate a build script into YAML files listing what it analyzes and simulates.
  #  ProFileToBuild - Path to the build script (`*.pro`) of the design.
  #  FilePath       - Directory to write the YAML files to.
  #
  # Runs [CreateDryRunDict] on $ProFileToBuild and writes `AnalyzeDict` to `<name>_Analyze.yml` and `SimulateDict` to
  # `<name>_Simulate.yml`, where `<name>` is the build script's file name without extension.
  #
  # See also: [CreateDryRunDict] [ProToJson]

  # Create AnalyzeDict and SimulateDict for the ProFileToBuild script
  variable AnalyzeDict
  variable SimulateDict
  CreateDryRunDict $ProFileToBuild

  set ProFileName [file rootname [file tail $ProFileToBuild]]

  # Convert Analyze Dict to Yaml via Huddle
  # {library [file {name language_ver}]}
  set AnalyzeHud [huddle compile {dict * {list {dict}}} $::osvvm::AnalyzeDict]
  set    AnalyzeYamlFile   [open [file join $FilePath "${ProFileName}_Analyze.yml"] w]
  puts  $AnalyzeYamlFile   [yaml::huddle2yaml $AnalyzeHud]
  close $AnalyzeYamlFile

  # Convert Simulate Dict to Yaml via Huddle
  # {library [file {name language_ver}]}
  set SimulateHud [huddle compile {dict * {list {dict}}} $::osvvm::SimulateDict]
  set    SimulateYamlFile   [open [file join $FilePath "${ProFileName}_Simulate.yml"] w]
  puts  $SimulateYamlFile   [yaml::huddle2yaml $SimulateHud]
  close $SimulateYamlFile
}

proc ProToJson {ProFileToBuild {FilePath "."}} {
  # Translate a build script into JSON files listing what it analyzes and simulates.
  #  ProFileToBuild - Path to the build script (`*.pro`) of the design.
  #  FilePath       - Directory to write the JSON files to.
  #
  # Runs [CreateDryRunDict] on $ProFileToBuild and writes `AnalyzeDict` to `<name>_Analyze.json` and `SimulateDict` to
  # `<name>_Simulate.json`, where `<name>` is the build script's file name without extension.
  #
  # See also: [CreateDryRunDict] [ProToYaml]

  # Create AnalyzeDict and SimulateDict for the ProFileToBuild script
  variable AnalyzeDict
  variable SimulateDict
  CreateDryRunDict $ProFileToBuild

  set ProFileName [file rootname [file tail $ProFileToBuild]]

  # Convert Analyze Dict to Yaml via Huddle
  # {library [file {name language_ver}]}
  set AnalyzeHud [huddle compile {dict * {list {dict}}} $::osvvm::AnalyzeDict]
  set    AnalyzeJsonFile   [open [file join $FilePath "${ProFileName}_Analyze.json"] w]
  puts  $AnalyzeJsonFile   [huddle jsondump $AnalyzeHud]
  close $AnalyzeJsonFile

  # Convert Simulate Dict to Yaml via Huddle
  # {library [file {name language_ver}]}
  set SimulateHud [huddle compile {dict * {list {dict}}} $::osvvm::SimulateDict]
  set    SimulateJsonFile   [open [file join $FilePath "${ProFileName}_Simulate.json"] w]
  puts  $SimulateJsonFile   [huddle jsondump $SimulateHud]
  close $SimulateJsonFile
}


# Don't export the following due to conflicts with Tcl built-ins
# map

namespace export CreateDryRunDict
namespace export CreateVhdlLsToml
namespace export CreateAnalyzeOrderCsv
namespace export ProToYaml
namespace export ProToJson


# end namespace ::osvvm
}
