.. # Load pre-defined aliases and graphical characters like © from docutils
   # <file> is used to denote the special path
   # <Python>\Lib\site-packages\docutils\parsers\rst\include
.. include:: <isonum.txt>
.. include:: <mmlalias.txt>

.. # |br| and |hr| and the style roles (:bolditalic:, :underline:, :strike:, :xlarge:, :red:, :green:, :blue:,
   # :purple:, :deletion:, :addition:) are registered by the 'pyTooling.Sphinx' extension.

.. role:: tclcode(code)
   :language: tcl
   :class: highlight
